### ISSUE TITLE
Game Failing to load

### ISSUE THREAD

**Issue by BaconCowReal** [tracer4b/nomi-ceu#279] opened 2023-03-09 01:32 UTC
For some reason, I've never messed with the pack files or nothing. I installed and tried to play but it gave me an error saying "Minecraft has encountered an error and cannot load further. Minecraft has narrowed it down to three possible things. Minecraft Forge, NuclearCraft, Forge Mod Loader

**Pack Version:**
manual-build

**Launcher:**
Curseforge
**Mode:**
None, didn't get to play

**Environment:**
None

**Description:**
Crashed because of three things

**Expected Behavior:**
To open and let me play the game

**Steps To Reproduce:**
I could send you the folder and you open it 

**Crash Log:**
[2023-03-08-2.log.gz](https://github.com/tracer4b/nomi-ceu/files/10926798/2023-03-08-2.log.gz)

**Screenshots:**
none

**Comment by IntegerLimit** [comment] 2023-03-09 10:45
Try using another launcher, aka Prism. This has happened before, and the main reason is because CurseForge launcher uses a weird version of java, which breaks a lot of things. Please move your instance to another launcher, like Prism Launcher. Duplicate of #221.

**Closed by IntegerLimit** 2023-03-09 10:45 UTC
Labels: bug
