### ISSUE TITLE
ServerFiles 1.4.3a and Client 1.4.3 incompatible.

### ISSUE THREAD

**Issue by Possemaster** [tracer4b/nomi-ceu#200] opened 2023-01-13 12:53 UTC
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.4.3 Curseforce Launcher

**Description:**
Installed Server 1.4.3a, Installed CLient 1.4.3 (latest) start game, Try to login to server. Incompatible (Requires LoliASM 5.6 CLient has 5.2)

**Expected Behavior:**
Login success

**Steps To Reproduce:**
As stated above

**Crash Log:**
If your client crashed as a result of this bug, please upload the generated crash log. This is found in your launcher's Nomifactory profile (aka instance) in a folder called `crash-reports`. If there was no crash, but instead an error screen, please upload your `latest.log` instead.

**Screenshots:**
![image](https://user-images.githubusercontent.com/7541145/212324391-b5171dc9-d0c1-446b-8f29-9e8fdfd16140.png)

**Comment by IntegerLimit** [comment] 2023-01-13 22:25
Fixed in 8b93aa71d3b63715176fe564a170a2be99c42951 I think.

**Comment by tracer4b** [comment] 2023-01-14 11:42
Duplicate of #182

**Closed** 2023-01-15 03:13 UTC
