### ISSUE TITLE
Naquadah reactor MK II crashes

### ISSUE THREAD

**Issue by nightshard** [tracer4b/nomi-ceu#249] opened 2023-02-11 08:27 UTC
V 1.4.2

Placing bolts of either refined naquadah or naquadria in a naquadah reactor MK II crashes the game, tried separately in two different built reactors, tried with 4A UV dynamo hatch and 1A UV dynamo hatch with same result.
[crash-2023-02-11_09.59.16-server.txt](https://github.com/tracer4b/nomi-ceu/files/10712929/crash-2023-02-11_09.59.16-server.txt)

**Comment by IntegerLimit** [comment] 2023-02-11 08:39
Fixed in 1.4.3 or 1.5, I can't remember. Update your instance, or you can wait until the next update, which should release sometime tomorrow or Monday. Duplicate of #169

**Closed by IntegerLimit** 2023-02-11 08:39 UTC
