### ISSUE TITLE
Cant craft rubber sheets

### ISSUE THREAD

**Issue by kotek900** [tracer4b/nomi-ceu#201] opened 2023-01-14 21:10 UTC
**Pack Version:**
1.5

**Description:**
crafting recipe for rubber sheets isn't working

**Expected Behavior:**
two rubber and one use of the hammer should make rubber sheets 

**Steps To Reproduce:**
attempt to craft rubber sheets in a crafting table

**Screenshots:**
rubber sheets in jei:
![image](https://user-images.githubusercontent.com/43883812/212496938-2793f0dc-ef52-481c-b763-bdcb5aca3881.png)
same recipe (after clicking the + button) in the crafting table:
![image](https://user-images.githubusercontent.com/43883812/212496970-a72186fd-1744-4f89-a50f-ed40103994ea.png)

**Comment by JadenKorr** [comment] 2023-01-14 21:18
I can confirm this bug. I was about to make an issue when I saw this one.

**Comment by JadenKorr** [comment] 2023-01-14 21:51
@tracer4b @IntegerLimit This issue breaks early game progression, since there is no other way to get rubber sheets to build your first machines.

**Comment by Spike1302** [comment] 2023-01-14 23:10
Also having this issue

**Comment by IntegerLimit** [comment] 2023-01-14 23:29
Huh, I'll have a look at it. I'm not sure why this is happening, as looking at the code, it is the same as the one for LuV Machine Casings manually, which seems to work.

**Comment by gmartens** [comment] 2023-01-15 03:12
Go to /scripts/normalmode.zs and find the "Rubber by hand" recipe.
Replace the "ore:craftingToolHammer" with "gregtech:hammer".

**Comment by Jadeon** [comment] 2023-01-15 03:36
> Go to /scripts/normalmode.zs and find the "Rubber by hand" recipe. Replace the "ore:craftingToolHammer" with "gregtech:hammer".

This fix works temporarily but only works with the iron version of the hammer in my testing so far.

**Comment by gmartens** [comment] 2023-01-15 03:40
Interesting. It is working for me on any full durability hammer, just not damaged ones.
If you look at the hammer advanced tooltip, there is no oredict tag on damaged hammers, this is probably the root of the problem.

**Comment by Jadeon** [comment] 2023-01-15 03:47
> 

You are correct it will on any full durability hammer.  Once the hammer has been used at least once it ceases to function:
https://gyazo.com/343ab5d86f03fab7dc3eafe8b5de03c2

**Comment by Jadeon** [comment] 2023-01-15 03:55
> Go to /scripts/normalmode.zs and find the "Rubber by hand" recipe. Replace the "ore:craftingToolHammer" with "gregtech:hammer".

This is close to correct instead replace it with "ore:gtceHardHammers" and all will function correctly.

**Comment by LemurVladimir** [comment] 2023-01-15 14:02
> > Go to /scripts/normalmode.zs and find the "Rubber by hand" recipe. Replace the "ore:craftingToolHammer" with "gregtech:hammer".
> 
> This is close to correct instead replace it with "ore:gtceHardHammers" and all will function correctly.

Affirmative, this change fixes the issue.

**Comment by windowsagent** [comment] 2023-01-20 19:02
> > > Go to /scripts/normalmode.zs and find the "Rubber by hand" recipe. Replace the "ore:craftingToolHammer" with "gregtech:hammer".
> > 
> > 
> > This is close to correct instead replace it with "ore:gtceHardHammers" and all will function correctly.
> 
> Affirmative, this change fixes the issue.

Can confirm too, this does solve the issue. Not sure if it breaks something with hard mode of Nomi though...

**Comment by IntegerLimit** [comment] 2023-01-20 22:30
It'll be fixed next update. This will not change anything in HM, as this is the loading script for NM.

**Comment by IntegerLimit** [comment] 2023-01-24 07:06
Fixed in https://github.com/tracer4b/nomi-ceu/commit/22bc16fe18eefd082e6492d0adbbbac732562c88. For now, change line 307 of normalmode.zs from 
`recipes.addShaped(<metaitem:plateRubber>,[[<ore:craftingToolHammer>],[<metaitem:rubber_drop>],[<metaitem:rubber_drop>]]);`
to
`recipes.addShaped(<metaitem:plateRubber>,[[<ore:gtceHardHammers>],[<metaitem:rubber_drop>],[<metaitem:rubber_drop>]]);`

**Closed by IntegerLimit** 2023-01-24 07:06 UTC
