### ISSUE TITLE
Some turbine rotors are broken.

### ISSUE THREAD

**Issue by trainvoi** [tracer4b/nomi-ceu#219] opened 2023-01-22 19:28 UTC
**Description:**
Searching for the recipes for turbine rotors shows that there are some turbine rotors that can be assembled with the Assembler, but their tooltips are broken and if you tried to craft one of these rotors, and hover your mouse over the rotor, the game will crashes.

**Crash Log:**
[2023-01-22-2.log.gz](https://github.com/tracer4b/nomi-ceu/files/10475285/2023-01-22-2.log.gz)
https://mclo.gs/tz5GLgL

**Screenshots:**
![image](https://user-images.githubusercontent.com/51245052/213935795-8f47a127-9def-4f76-bd9c-3e569224457f.png)

**Comment by IntegerLimit** [comment] 2023-01-22 22:08
Duplicate of #206. It will be fixed next update.

**Comment by IntegerLimit** [comment] 2023-01-24 06:43
Duplicate of #206. Also, like I said before, it will be fixed next update.

**Closed by IntegerLimit** 2023-01-24 06:43 UTC
