### ISSUE TITLE
Black Steel Dust Recipe broken

### ISSUE THREAD

**Issue by danirpg** [tracer4b/nomi-ceu#84] opened 2022-08-25 17:58 UTC
**Pack Version:**
1.4.0

**Description:**
The recipe of Black Steel Dust is broken, it might be the red coal cuz the NBT is not matching with the recipe item?

**Expected Behavior:**
Recipe in mixer results on black steel dust

**Steps To Reproduce:**
Put the recipe items of black steel dust in the MV mixer.

**Crash Log:**
No crash.

**Screenshots:**
![image](https://user-images.githubusercontent.com/15187376/186736159-cae7771d-ae96-45c4-af78-59ed02b53d5b.png)

**Comment by okjijenAbi** [comment] 2022-09-01 20:30
It is because of the NBT tag, when getting red coal from creative inventory works just fine.

**Comment by tong-ge** [comment] 2022-09-04 13:13
I'm reproducing this issue too. My tech is stuck.

**Comment by ES-BitJump** [comment] 2022-09-04 13:28
Is there any solution to this problem?

**Comment by tong-ge** [comment] 2022-09-05 04:44
I sent a pull request to convert NBT-ed red coals to non-NBT-ed ones, which could be a temporary solution.

**Comment by tracer4b** [comment] 2022-10-01 12:15
Closed in 89424eed0a1a4348939b8b1f3927298770a02ca1

**Closed by tracer4b** 2022-10-01 12:15 UTC
