### ISSUE TITLE
Small Plate Presser recipe tab still viewable

### ISSUE THREAD

**Issue by pat2rome** [tracer4b/nomi-ceu#45] opened 2022-06-11 01:14 UTC
**Pack Version:**
1.2.3a

**Description:**
Even though the Small Plate Presser from Advanced Rocketry appears to be disabled (as it does not appear in JEI), the recipe tab is still viewable.

**Expected Behavior:**
No recipe tab should exist for a machine that doesn't exist.

**Steps To Reproduce:**
Look through the recipes for Gregtech Iron Ore (hover over it in JEI and press "U") and navigate through the recipe tabs. The Small Plate Presser tab is labeled with a white "Sm".

**Screenshots:**
![Screenshot](https://i.imgur.com/bAtAtj5.png)

**Comment by pat2rome** [comment] 2022-06-11 01:16
I also noticed that this is the case for the SAG Mill (the tab immediately to the left), so it's probably a recurring issue. Seems like a quick way to determine which ones are an issue at a glance is the tabs for disabled machines have the text instead of a picture of the machine.

**Comment by tracer4b** [comment] 2022-06-13 08:08
I can't reproduce the issue with a fresh install of version 1.3. Try updating cleanly
![image](https://user-images.githubusercontent.com/61507029/173308687-c113b4d0-1c81-4a00-a1fc-22a0ab6da97e.png)

**Comment by Folanlron** [comment] 2022-06-15 00:43
This seems to be an issue when switching resource packs in the game..

I just switched mine and the Small Presser/SAG JEI panels showed up

**Comment by tracer4b** [comment] 2022-06-16 03:13
I'm going to blame HEI/JEI and close this

**Closed by tracer4b** 2022-06-16 03:13 UTC
