### ISSUE TITLE
Tooltip for several Turbine Rotors say "Tooltip broken, check log"

### ISSUE THREAD

**Issue by felix-schneider** [tracer4b/nomi-ceu#239] opened 2023-02-04 12:43 UTC
**Pack Version:**
1.5

**Description:**
This is the case for
* Chrome
* Manganese
* Molybdenum
* Neodynium
* Osmium
* Tungsten
* Naquadah
* Tritanium
* Brass
* Magnalium
* Sterling Silver
* Black Bronze
* Bismuth Bronze
* Osmiridium
* Rhodium-Plated Lumium-Palladium
* HSS-G
* HSS-S

Log says (this one is for chrome)
```
[13:40:49] [Client thread/ERROR] [HadEnoughItems]: Failed to get tooltip: 1xitem.meta_item@711 gregtech:meta_item_1 nbt:{GT.PartStats:{Material:"chrome"}}
java.lang.IllegalArgumentException: Material chrome does not have a tool harvest level! Is probably not a Tool Material
	at gregtech.api.unification.material.Material.getToolHarvestLevel(Material.java:192) ~[Material.class:?]
	at gregtech.common.items.behaviors.AbstractMaterialPartBehavior.addInformation(AbstractMaterialPartBehavior.java:77) ~[AbstractMaterialPartBehavior.class:?]
	at gregtech.common.items.behaviors.TurbineRotorBehavior.addInformation(TurbineRotorBehavior.java:59) ~[TurbineRotorBehavior.class:?]
	at gregtech.api.items.metaitem.MetaItem.addInformation(MetaItem.java:577) ~[MetaItem.class:?]
	at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:707) ~[aip.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.getTooltip(ItemStackRenderer.java:43) [ItemStackRenderer.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.getTooltip(ItemStackRenderer.java:24) [ItemStackRenderer.class:?]
	at mezz.jei.gui.ingredients.GuiIngredient.drawTooltip(GuiIngredient.java:208) [GuiIngredient.class:?]
	at mezz.jei.gui.ingredients.GuiIngredient.drawOverlays(GuiIngredient.java:191) [GuiIngredient.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.drawOverlays(RecipeLayout.java:202) [RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipesGui.drawScreen(RecipesGui.java:230) [RecipesGui.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124) [buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3614) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_351]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_351]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_351]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_351]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

This may be a GTCEu problem

**Comment by Folanlron** [comment] 2023-02-04 21:19
Will be fixed in next release..

https://github.com/tracer4b/nomi-ceu/issues/206

**Comment by IntegerLimit** [comment] 2023-02-04 22:15
Duplicate of https://github.com/tracer4b/nomi-ceu/issues/206. Fixed next GTCEu.

**Closed by IntegerLimit** 2023-02-04 22:15 UTC
Labels: bug, duplicate
