### ISSUE TITLE
[Hard] Rubber sheet alloy furnace recipe does not appear in JEI.

### ISSUE THREAD

**Issue by pudy248** [tracer4b/nomi-ceu#114] opened 2022-10-01 03:22 UTC
In short, looking for rubber sheet recipes in JEI leads one to believe that there is no pre-LV way to make them, despite rubber sheets being required for LV machines. Putting the ingots in a steam alloy smelter with a plate mold does work, but it doesn't show up in JEI. This has caused several people no small amount of confusion.

**Comment by tracer4b** [comment] 2022-10-01 11:55
Duplicate of GregTechCEu/GregTech#1163

**Closed by tracer4b** 2022-10-01 11:55 UTC
